[package]
name = "m6-starnix-elf-parse"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Starnix-fork shim: elf_parse (M6 no_std)"

[lib]
name = "elf_parse"

[dependencies]
zx = { package = "m6-zx-shim", path = "../m6-zx-shim" }
bitflags = "2"
num-traits = { version = "0.2", default-features = false }
num-derive = "0.4"
static_assertions = "1"
zerocopy = { workspace = true }
